export const cartTypes = {
    TOGGLE_CART_VIEW : 'TOGGLE_CART_VIEW',
    ADD_TO_CART : 'ADD_TO_CART',
    CLEAR_ITEMS_CHECKOUT : 'CLEAR_ITEMS_CHECKOUT',
    REDUCE_ITEM_QUANTITY : 'REDUCE_ITEM_QUANTITY'
}